"""
Django settings for prroyectociudad project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j%b+pgnmpa7kqe)ic$q4n6kzus1a2^s=wa$!e-4r&h%md-1!hs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ordenamiento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prroyectociudad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prroyectociudad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Jazzmin settings

JAZZMIN_SETTINGS = {
    "site_title": "Ordenamiento Territorial",  # Título del navegador
    "site_header": "Panel de Administración",  # Cabecera del admin
    "site_brand": "CiudadApp",                 # Texto del menú superior

    # Logo opcional (coloca una imagen en static/ordenamiento/logo.png)
    "site_logo": None,  # Solo si tienes el archivo en static

    "welcome_sign": "Bienvenido al sistema de gestión territorial",
    "copyright": "CiudadApp",

    # Permite buscar desde la barra superior
    "search_model": ["ordenamiento.Parroquia", "ordenamiento.Barrio"],

    # Enlaces del menú superior
    "topmenu_links": [
        {"name": "Inicio", "url": "index", "permissions": ["auth.view_user"]},
        {"model": "ordenamiento.parroquia"},
        {"model": "ordenamiento.barrio"},
    ],

    # Íconos de Font Awesome para cada modelo
    "icons": {
        "ordenamiento.Parroquia": "fas fa-map-marked-alt",
        "ordenamiento.Barrio": "fas fa-city",
    },

    # Mostrar barra lateral y expandirla por defecto
    "show_sidebar": True,
    "navigation_expanded": True,

    # Agrupar los modelos bajo un nombre personalizado de app (opcional)
    "app_labels": {
        "ordenamiento": "Gestión Territorial"
    },

    # Orden opcional de modelos en la barra lateral
    "order_with_respect_to": ["ordenamiento.Parroquia", "ordenamiento.Barrio"],
}


